#!/bin/sh

set -e

git submodule update

mkdir -p sdl

cd submodules/SDL

rm -rf build

cmake -S . -B build \
  -DCMAKE_C_COMPILER=gcc \
  -DCMAKE_CXX_COMPILER=/usr/bin/g++ \
  -DSDL_STATIC=OFF \
  -DSDL_SHARED=ON \
  -DSDL_LIBC=ON \
  -DSDL_DBUS=OFF \
  -DSDL_LIBURING=OFF \
  -DSDL_DISKAUDIO=OFF \
  -DSDL_DUMMYAUDIO=OFF \
  -DSDL_DUMMYVIDEO=ON \
  -DSDL_IBUS=OFF \
  -DSDL_OPENGL=OFF \
  -DSDL_OPENGLES=OFF \
  -DSDL_PTHREADS=ON \
  -DSDL_PTHREADS_SEM=ON \
  -DSDL_OSS=OFF \
  -DSDL_ALSA=OFF \
  -DSDL_ALSA_SHARED=OFF \
  -DSDL_JACK=OFF \
  -DSDL_JACK_SHARED=OFF \
  -DSDL_PIPEWIRE=OFF \
  -DSDL_PIPEWIRE_SHARED=OFF \
  -DSDL_PULSEAUDIO=OFF \
  -DSDL_PULSEAUDIO_SHARED=OFF \
  -DSDL_SNDIO=OFF \
  -DSDL_SNDIO_SHARED=OFF \
  -DSDL_RPATH=OFF \
  -DSDL_CLOCK_GETTIME=OFF \
  -DSDL_X11=ON \
  -DSDL_X11_SHARED=OFFON \
  -DSDL_WAYLAND=ON \
  -DSDL_WAYLAND_SHARED=ON \
  -DSDL_WAYLAND_LIBDECOR=OFF \
  -DSDL_WAYLAND_LIBDECOR_SHARED=OFF \
  -DSDL_RPI=OFF \
  -DSDL_ROCKCHIP=OFF \
  -DSDL_COCOA=OFF \
  -DSDL_DIRECTX=OFF \
  -DSDL_XINPUT=OFF \
  -DSDL_WASAPI=OFF \
  -DSDL_RENDER_D3D=OFF \
  -DSDL_RENDER_D3D11=OFF \
  -DSDL_RENDER_D3D12=OFF \
  -DSDL_RENDER_METAL=OFF \
  -DSDL_RENDER_GPU=ON \
  -DSDL_VIVANTE=OFF \
  -DSDL_VULKAN=ON \
  -DSDL_RENDER_VULKAN=ON \
  -DSDL_METAL=OFF \
  -DSDL_OPENVR=OFF \
  -DSDL_KMSDRM=OFF \
  -DSDL_KMSDRM_SHARED=OFF \
  -DSDL_OFFSCREEN=OFF \
  -DSDL_DUMMYCAMERA=OFF \
  -DSDL_HIDAPI=ON \
  -DSDL_HIDAPI_LIBUSB=OFF \
  -DSDL_HIDAPI_LIBUSB_SHARED=OFF \
  -DSDL_HIDAPI_JOYSTICK=OFF \
  -DSDL_VIRTUAL_JOYSTICK=OFF \
  -DSDL_LIBUDEV=ON \
  -DSDL_ASAN=OFF \
  -DSDL_CCACHE=ON \
  -DSDL_CLANG_TIDY=OFF \
  -DSDL_GPU_DXVK=OFF

cmake --build build

cmake --install build --prefix=../../.sdl3
