name: Build and Upload Artifact

on:
  push:
    branches:
      - "*"
      - "*/*"
      - "**"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y build-essential cmake gcc g++ git make \
               pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev \
               libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev \
               libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev \
               libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev \
               libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev fcitx-libs-dev \
               libpipewire-0.3-dev libwayland-dev libdecor-0-dev liburing-dev
      - name: Run make
        run: make
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: .out/app/zig-zag-zoe
          retention-days: 1
      - name: Upload flatpak
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: .out/ZigZagZoe.flatpak
          retention-days: 1
