name: Build and Upload Artifact

on:
  push:
    branches:
      - */*
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake gcc g++
    - name: Run make
      run: make
    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: .out/app/zig-zag-zoe
        retention-days: 1
    - name: Upload flatpak
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: .out/ZigZagZoe.flatpak
        retention-days: 1
